### PR TITLE
Current line highlighter

### PR DESCRIPTION
**Pull request by andyarvanitis**
Hi Dave,

Nice job on this!

I have a plugin that I finally got around to refactoring as a XCFixin. I've been using it in one form or another for quite some time, and believe it to be pretty stable. This version has been tested on Xcode 4.2.x and 4.3.x (and even 4.4). If it looks like something you'd like included with your stuff, please feel free to pull it in. Also let me know if you spot anything that needs changing before doing so.

Thanks,
-andy

### CODE REVIEW

**Comment by tom-seddon** [comment]
Hi Andy,

I've merged this in to my fork, and it's been working fine for me for the last week or so - I like it a lot! Only change I had to make was to the pbxproj file - XCFixin.\* were referenced with absolute paths for some reason.

I'm not sure where David is, but I can push to the main repository too, so I'll do that in the next day or so.

--Tom

**Comment by andyarvanitis** [comment]
Hi Tom,

Great, thanks! Glad you're finding it useful. I haven't tried your
scripts plugin yet, but I definitely plan to.

-andy

On Thu, Apr 26, 2012 at 5:00 AM, Tom Seddon
reply@reply.github.com
wrote:

**Comment by tom-seddon** [comment]
OK, all done!

Thanks,

--Tom

**Comment by davekeck** [comment]
Hey Andy, sorry for the delay and thanks for the CurrentLineHighlighter contribution (and thanks to you Tom for taking care of it.)

Andy, I just added you as a collaborator so you should have full push access. Cheers!

**Comment by andyarvanitis** [comment]
No problem at all! Thanks guys!
-andy

**Pull request merged**
