### PR TITLE
User Scripts fixin

### PR DESCRIPTION
**Pull request by tom-seddon**
I managed to put together some semblance of the User Scripts menu fixin that I was hoping to do. It was actually easier than I was expecting, once I'd figured out how to actually get the text view. Still needs a bit of work, but it's already useful... and I think I've had enough class-dump output for this weekend.

This new pull request appears to include my XCFixin.m fix again. So apologies if you're getting that particular patch twice. (I've only ever used git on my own, and I'm not terribly familiar with github...)

Thanks,

--Tom

P.S. tested with Xcode 4.3.2; should work with 4.3.1 as well. I only upgraded last night and the fixin was already mostly working by that point.

### CODE REVIEW

**Comment by davekeck** [comment]
Hey Tom, awesome work! I just merged the UserScripts fixin into the repo. I also added you as a collaborator, so you should (?) be able to push directly to the project if you care to. Let me know if you have issues, I've never used that feature before.

Really like the UserScripts fixin. Over the next week or so I was thinking I might try implementing a dialog similar to the Xcode 3 one that permits easy editing of scripts, editing key-equivalents, etc.

Also, I created a distinction between stable and experimental plugins, where stable ones are built as a part of the workspace. I categorized the UserScripts fixin as experimental, so I'm thinking once there's a dialog and a little more testing I'll make it 'stable'.

Cheers!

David

**Comment by tom-seddon** [comment]
Configuration dialog sounds like an excellent idea :) I've got very little Cocoa UI experience, which is why the scripts fixin UI is a bit... spartan.

I fixed a couple of things last night so I'll get everything in sync then figure out how to push them to the main branch now.

--Tom

**Comment by tom-seddon** [comment]
OK - it looks like I've managed to push my changes to your repo, so that seemed to work!

Changes:
- scripts now work if you have multiple windows or tabs showing the same document
- scripts work in the Version editor
- new mode for scripts so they can receive the text of the current line if there's no active selection (always wanted this in Xcode3!)

--Tom

**Comment by davekeck** [comment]
> OK - it looks like I've managed to push my changes to your repo, so that seemed to work!
> 
> Changes:
> - scripts now work if you have multiple windows or tabs showing the same document
> - scripts work in the Version editor
> - new mode for scripts so they can receive the text of the current line if there's no active selection (always wanted this in Xcode3!)

Good to hear Tom - it's cool to have another person on board :).
Reading the Apple mailing lists, the scripts menu has been one of the
biggest issues people have with Xcode 4 - a lot of people will surely
love it.

David

**Pull request merged**
