### PR TITLE
Some Changes

### PR DESCRIPTION
**Pull request by BrunoBerisso**
Hi.

First thank you very much for this project. It made my life happier :)
Here are some changes i need to made to continue using the Fixins. The important one is the last commit about make the project compile in the last version of XCode.

The other one is remove the toggle logic from the "Hide Distractions" fix, i made it because XCode alway pop some pane and i have to hit the shortcut twice to hide all again. I personally find it much more confortable this way.

And the other one only add "xcshareddata" to the .gitignore.

Best regards,
Bruno

### CODE REVIEW

**Comment by azav** [comment]
I have to be doing something wrong.  I just pulled your master from your github, did a build all 64 bit, got the "should be OK" message for all plugins and relaunched Xcode.  Instant crash in loadPluginBundle.

**Comment by azav** [comment]
FYI, I am under 10.8.5 since 10.9 has too many distracting animations I can't turn off.

**Comment by BrunoBerisso** [comment]
Hmm... maybe the issue is because the OSX version. I'm running 10.9.2 and it's working fine. In fact i'm have to do the conversion to ARC because XCode refuse to compile the project. I will take a closer look...

**Comment by BrunoBerisso** [comment]
This PR is so old that I'm emotionally attached to it 😆
Thanks for this project, was a _must have_ for a long time for me.

**Pull request closed without merging**
