### PR TITLE
added a new fix in : CustomizeWarningErrorHighlights

### PR DESCRIPTION
**Pull request by armadillu**
Customize the inline error/warning message highlight color. Useful if want to be able to read your code's inline warning/errors when using a dark background color.

See here http://www.flickr.com/photos/armadillu/6999372818/in/photostream

### CODE REVIEW

**Comment by supermarin** [comment]
@davekeck any updates on this? We'd like to have it in [Alcatraz](http://github.com/mneorr/Alcatraz)  :)

**Comment by tom-seddon** [comment]
I can't do this right now, but I should be able to find the time in the next day or two. Sorry for the delay!

--Tom

**Comment by supermarin** [comment]
@tom-seddon awesome, thanks!

**Comment by tom-seddon** [comment]
OK, done!

Sorry for the delay - I'm not using Mac OS X much at the moment.

--Tom

**Pull request merged**
